
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "SimachewD - ADMIN",
  description: "Generated by create next app",
};

export default function AdminLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
        <main className="">
          {children}
        </main>
  );
}
